In [2]:
import pandas as pd
df=pd.read_csv("intern/input/main.csv")
df.head()

,SKU,DESCRIPTION,YEAR,CAPACITY,URL,PRICE,SELLER_INFORMATION,OFFER_DESCRIPTION,COUNTRY
0,11331,"Barbaresco,Angelo Gaja",1990,750ml,https://www.wine-searcher.com/find/barbaresco+...,$295.00,TopWines Switzerland SA,1990Barbaresco Gaja Angelo,Switzerland
1,11331,"Barbaresco,Angelo Gaja",1990,750ml,https://www.wine-searcher.com/find/barbaresco+...,$324.62,Vintage Grand Cru,Gaja Barbaresco1990,Hong Kong
2,11331,"Barbaresco,Angelo Gaja",1990,750ml,https://www.wine-searcher.com/find/barbaresco+...,$329.00,The Redd Collection,"1990Barbaresco,Angelo Gaja",USA (CA)
3,11331,"Barbaresco,Angelo Gaja",1990,750ml,https://www.wine-searcher.com/find/barbaresco+...,$338.68,Wine Walker (HK) Limited,"Gaja Barbaresco,1990,Italy,Piedmont",Hong Kong
4,11331,"Barbaresco,Angelo Gaja",1990,750ml,https://www.wine-searcher.com/find/barbaresco+...,$396.83,Enoteca Properzio,Barbaresco Gaja19900.75lt.,Italy

In [3]:
df.set_index("SKU", inplace = True)
filt=df[df['COUNTRY'].str.contains("USA")]
filt

,DESCRIPTION,YEAR,CAPACITY,URL,PRICE,SELLER_INFORMATION,OFFER_DESCRIPTION,COUNTRY
SKU,,,,,,,,
11331,"Barbaresco,Angelo Gaja",1990,750ml,https://www.wine-searcher.com/find/barbaresco+...,$329.00,The Redd Collection,"1990Barbaresco,Angelo Gaja",USA (CA)
11332,"Barbaresco,Angelo Gaja",2010,750ml,https://www.wine-searcher.com/find/barbaresco+...,$175.00,The Redd Collection,"2010Barbaresco,Angelo Gaja",USA (CA)
11333,"Barbaresco,Costa Russi,Angelo Gaja",2009,750ml,https://www.wine-searcher.com/find/barbaresco+...,$304.00,The Redd Collection,"2009Barbaresco,Costa Russi,Angelo Gaja",USA (CA)
11333,"Barbaresco,Costa Russi,Angelo Gaja",2009,750ml,https://www.wine-searcher.com/find/barbaresco+...,$359.99,Lynnway Liquor Mart,Gaja Costa Russi Barbaresco20092009750ml,USA (MA)
11333,"Barbaresco,Costa Russi,Angelo Gaja",2009,750ml,https://www.wine-searcher.com/find/barbaresco+...,$379.00,The Old & Rare Wine Company,Angelo Gaja Costa Russi Langhe2009,USA (CA)
...,...,...,...,...,...,...,...,...
11625,"Dominio De Pingus,Peter Sisseck",2005,750ml,https://www.wine-searcher.com/find/dominio+de+...,$949.00,The Redd Collection,"2005Dominiode Pingus,Peter Sisseck",USA (CA)
11625,"Dominio De Pingus,Peter Sisseck",2005,750ml,https://www.wine-searcher.com/find/dominio+de+...,$980.00,Westgarth Wines,2005Pingus,USA (CA)
11625,"Dominio De Pingus,Peter Sisseck",2005,750ml,https://www.wine-searcher.com/find/dominio+de+...,$1499.00,Finding.Wine,Dominiode Pingus2005-Pingus750ml.,USA (FL)
11625,"Dominio De Pingus,Peter Sisseck",2005,750ml,https://www.wine-searcher.com/find/dominio+de+...,$1695.00,Cellaraiders,2005Pingus,USA (NY)
11625,"Dominio De Pingus,Peter Sisseck",2005,750ml,https://www.wine-searcher.com/find/dominio+de+...,$5875.00,Westgarth Wines,2005Pingus,USA (CA)

In [4]:
filt.to_csv('filteredCountry.csv')

In [5]:
print(df['PRICE'].dtypes)

object

In [6]:
df1=pd.read_csv("filteredCountry.csv")
df1.head()
df1["PRICE"]=df1['PRICE'].str.replace("$","")
df1["PRICE"]=pd.to_numeric(df1["PRICE"],errors = 'coerce')
df1.head()
print(df1['PRICE'].dtypes)

float64

In [7]:
df2=df1.groupby('SKU').apply(lambda df: df.nsmallest(2, 'PRICE'))
df2[['PRICE']]

             PRICE
SKU
11331 0     329.00
11332 1     175.00
11333 2     304.00
      3     359.99
11334 8     329.00
...            ...
11622 3004  499.00
11624 3014  500.00
      3015  525.00
11625 3024  750.00
      3025  949.00

[545 rows x 1 columns]